import { blogsDetails } from "./blog-details";

import { generateImgPath } from "./data";

export const filterBlog = (slug) =>
  blogsGrid.find((item) => item.slug === slug);
export const filterBlogDetail = (slug) =>
  blogsDetails.find((item) => item.slug === slug).detail;
export const dateWiseBlogs = (date) =>
  blogs.filter((item) => item.blogDate.includes(date));
export const categoryWiseBlogs = (category) =>
  blogs.filter((item) => item.categories.includes(category));
export const tagsWiseBlogs = (tag) =>
  blogs.filter((item) => item.tags.includes(tag));

export const blogTags = [
  {
    id: 3,
    slug: "comedies",
    name: "streamTag.comedy",
  },
   {
    id: 2,
    slug: "action",
    name: "streamBlogCategory.comedies",
  },
  {
    id: 4,
    slug: "drama",
    name: "streamTag.drama",
  },
  {
    id: 5,
    slug: "dramas",
    name: "streamTag.drama",
  },
  {
    id: 6,
    slug: "historical",
    name: "streamTag.history",
  },
  {
    id: 7,
    slug: "horr",
    name: "streamTag.horror",
  },
  {
    id: 9,
    slug: "movie",
    name: "streamBlogCategory.movy",
  },
  {
    id: 10,
    slug: "movie-trailers",
    name: "streamBlogCategory.movie_trailers",
  },
  {
    id: 13,
    slug: "thrill",
    name: "streamTag.thriller",
  },
  {
    id: 15,
    slug: "trailer",
    name: "streamBlogCategory.trailer",
  },
  {
    id: 16,
    slug: "tv rumors",
    name: "streamBlogCategory.tv_rumors",
  },
  {
    id: 17,
    slug: "tv series",
    name: "streamBlogCategory.tv_series",
  },
];

export const blogCategories = [
  {
    id: 1,
    title: "streamTag.drama",
    post_count: "4",
  },
  {
    id: 2,
    title: "streamTag.history",
    post_count: "7",
  },
  {
    id: 3,
    title: "streamBlogCategory.movy",
    post_count: "2",
  },
  {
    id: 4,
    title: "streamBlogCategory.movie_trailers",
    post_count: "6",
  },
  {
    id: 5,
    title: "streamBlogCategory.trailer",
    post_count: "4",
  },
  {
    id: 6,
    title: "streamBlogCategory.tv_comedies",
    post_count: "3",
  },
  {
    id: 7,
    title: "streamBlogCategory.tv_rumors",
    post_count: "4",
  },
  {
    id: 8,
    title: "streamBlogCategory.tv_series",
    post_count: "5",
  },
  {
    id: 8,
    title: "streamShop.uncategorized",
    post_count: "5",
  },
];

export const blogs = [
  {
    id: 1,
    thumbnail: generateImgPath("/assets/images/blog/rebirth-of-the-realm.webp"),
    blogDate: "January 10, 2025",
    userImage: generateImgPath("/assets/images/user/user3.webp"),
    username: "streamAccount.jenny",
    slug: "the-most-anticipated-movies",
    title: "streamBlog.blog1",
    description:"streamBlog.blog1_desc",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "streamBlogCategory.drama",
    tags: ["streamBlogTag.comedies", "streamTag.drama", "streamBlogCategory.movie_trailers"],
    category:["streamBlogCategory.history","streamBlogCategory.movy", "streamBlogCategory.trailer" ,"streamBlogCategory.tv_series"],
  },
  {
    id: 2,
    thumbnail: generateImgPath("/assets/images/blog/Special-Effects.webp"),
    blogDate: "January 10, 2025",
    userImage: generateImgPath("/assets/images/user/user3.webp"),
    username: "streamAccount.jenny",
    slug: "the-most-anticipated-movies",
    title: "streamBlog.blog2",
    description:"streamBlog.blog2_desc",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "streamBlogCategory.drama",
    tags: ["streamBlogTag.comedies", "streamTag.drama", "streamBlogCategory.movie_trailers"],
    category:["streamBlogCategory.history","streamBlogCategory.movy", "streamBlogCategory.trailer" ,"streamBlogCategory.tv_series"],
  },
  {
    id: 3,
    thumbnail: generateImgPath("/assets/images/blog/to-be-continue.webp"),
    blogDate: "January 10, 2025",
    userImage: generateImgPath("/assets/images/user/user3.webp"),
    username: "streamAccount.jenny",
    slug: "the-most-anticipated-movies",
    title: "streamBlog.blog3",
    description:"streamBlog.blog3_desc",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "streamBlogCategory.drama",
    tags: ["streamBlogTag.comedies", "streamTag.drama", "streamBlogCategory.movie_trailers"],
    category:["streamBlogCategory.history","streamBlogCategory.movy", "streamBlogCategory.trailer" ,"streamBlogCategory.tv_series"],
  },
  {
    id: 4,
    thumbnail: generateImgPath("/assets/images/blog/duos-standing.webp"),
    blogDate: "January 10, 2025",
    userImage: generateImgPath("/assets/images/user/user3.webp"),
    username: "streamAccount.jenny",
    slug: "the-most-anticipated-movies",
    title: "streamBlog.blog4",
    description:"streamBlog.blog4_desc",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "streamBlogCategory.drama",
    tags: ["streamBlogTag.comedies", "streamTag.drama", "streamBlogCategory.movie_trailers"],
    category:["streamBlogCategory.history","streamBlogCategory.movy", "streamBlogCategory.trailer" ,"streamBlogCategory.tv_series"],
  },
  {
    id: 5,
    thumbnail: generateImgPath("/assets/images/blog/short-movie.webp"),
    blogDate: "January 10, 2025",
    userImage: generateImgPath("/assets/images/user/user3.webp"),
    username: "streamAccount.jenny",
    slug: "the-most-anticipated-movies",
    title: "streamBlog.blog5",
    description:"streamBlog.blog5_desc",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "streamBlogCategory.drama",
    tags: ["streamBlogTag.comedies", "streamTag.drama", "streamBlogCategory.movie_trailers"],
    category:["streamBlogCategory.history","streamBlogCategory.movy", "streamBlogCategory.trailer" ,"streamBlogCategory.tv_series"],
  },
  {
    id: 6,
    thumbnail: generateImgPath("/assets/images/blog/beloved.webp"),
    blogDate: "January 10, 2025",
    userImage: generateImgPath("/assets/images/user/user3.webp"),
    username: "streamAccount.jenny",
    slug: "the-most-anticipated-movies",
    title: "streamBlog.blog6",
    description:"streamBlog.blog6_desc",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "streamBlogCategory.drama",
    tags: ["streamBlogTag.comedies", "streamTag.drama", "streamBlogCategory.movie_trailers"],
    category:["streamBlogCategory.history","streamBlogCategory.movy", "streamBlogCategory.trailer" ,"streamBlogCategory.tv_series"],
  },
  {
    id: 7,
    thumbnail: generateImgPath("/assets/images/blog/blog9.webp"),
    blogDate: "January 10, 2025",
    userImage: generateImgPath("/assets/images/user/user3.webp"),
    username: "streamAccount.jenny",
    slug: "the-most-anticipated-movies",
    title: "streamBlog.blog7",
    description:"streamBlog.blog7_desc",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "streamBlogCategory.drama",
    tags: ["streamBlogTag.comedies", "streamTag.drama", "streamBlogCategory.movie_trailers"],
    category:["streamBlogCategory.history","streamBlogCategory.movy", "streamBlogCategory.trailer" ,"streamBlogCategory.tv_series"],
  },
  {
    id: 8,
    thumbnail: generateImgPath("/assets/images/blog/blog8.webp"),
    blogDate: "January 10, 2025",
    userImage: generateImgPath("/assets/images/user/user3.webp"),
    username: "streamAccount.jenny",
    slug: "the-most-anticipated-movies",
    title: "streamBlog.blog8",
    description:"streamBlog.blog8_desc",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "streamBlogCategory.drama",
    tags: ["streamBlogTag.comedies", "streamTag.drama", "streamBlogCategory.movie_trailers"],
    category:["streamBlogCategory.history","streamBlogCategory.movy", "streamBlogCategory.trailer" ,"streamBlogCategory.tv_series"],
  },
  {
    id: 9,
    thumbnail: generateImgPath("/assets/images/blog/Independent.webp"),
    blogDate: "January 10, 2025",
    userImage: generateImgPath("/assets/images/user/user3.webp"),
    username: "streamAccount.jenny",
    slug: "the-most-anticipated-movies",
    title: "streamBlog.blog9",
    description:"streamBlog.blog9_desc",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "streamBlogCategory.drama",
    tags: ["streamBlogTag.comedies", "streamTag.drama", "streamBlogCategory.movie_trailers"],
    category:["streamBlogCategory.history","streamBlogCategory.movy", "streamBlogCategory.trailer" ,"streamBlogCategory.tv_series"],
  },
  {
    id: 10,
    thumbnail: generateImgPath("/assets/images/blog/blog5.webp"),
    blogDate: "January 10, 2025",
    userImage: generateImgPath("/assets/images/user/user3.webp"),
    username: "streamAccount.jenny",
    slug: "the-most-anticipated-movies",
    title: "streamBlog.blog10",
    description:"streamBlog.blog10_desc",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "streamBlogCategory.drama",
    tags: ["streamBlogTag.comedies", "streamTag.drama", "streamBlogCategory.movie_trailers"],
    category:["streamBlogCategory.history","streamBlogCategory.movy", "streamBlogCategory.trailer" ,"streamBlogCategory.tv_series"],
  },

  {
    id: 11,
    thumbnail: generateImgPath("/assets/images/blog/blog4.webp"),
    blogDate: "January 10, 2025",
    userImage: generateImgPath("/assets/images/user/user3.webp"),
    username: "streamAccount.jenny",
    slug: "the-most-anticipated-movies",
    title: "streamBlog.blog11",
    description:"streamBlog.blog11_desc",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "streamBlogCategory.drama",
    tags: ["streamBlogTag.comedies", "streamTag.drama", "streamBlogCategory.movie_trailers"],
    category:["streamBlogCategory.history","streamBlogCategory.movy", "streamBlogCategory.trailer" ,"streamBlogCategory.tv_series"],
  },

  {
    id: 12,
    thumbnail: generateImgPath("/assets/images/blog/comedy-movie.webp"),
    blogDate: "January 10, 2025",
    userImage: generateImgPath("/assets/images/user/user3.webp"),
    username: "streamAccount.jenny",
    slug: "the-most-anticipated-movies",
    title: "streamBlog.blog12",
    description:"streamBlog.blog12_desc",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "streamBlogCategory.drama",
    tags: ["streamBlogTag.comedies", "streamTag.drama", "streamBlogCategory.movie_trailers"],
    category:["streamBlogCategory.history","streamBlogCategory.movy", "streamBlogCategory.trailer" ,"streamBlogCategory.tv_series"],
  },

  {
    id: 13,
    thumbnail: generateImgPath("/assets/images/blog/kisds-movie.webp"),
    blogDate: "January 10, 2025",
    userImage: generateImgPath("/assets/images/user/user3.webp"),
    username: "streamAccount.jenny",
    slug: "the-most-anticipated-movies",
    title: "streamBlog.blog13",
    description:"streamBlog.blog13_desc",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "streamBlogCategory.drama",
    tags: ["streamBlogTag.comedies", "streamTag.drama", "streamBlogCategory.movie_trailers"],
    category:["streamBlogCategory.history","streamBlogCategory.movy", "streamBlogCategory.trailer" ,"streamBlogCategory.tv_series"],
  },

  {
    id: 14,
    thumbnail: generateImgPath("/assets/images/blog/blog1.webp"),
    blogDate: "January 10, 2025",
    userImage: generateImgPath("/assets/images/user/user3.webp"),
    username: "streamAccount.jenny",
    slug: "the-most-anticipated-movies",
    title: "streamBlog.blog14",
    description:"streamBlog.blog14_desc",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "streamBlogCategory.drama",
    tags: ["streamBlogTag.comedies", "streamTag.drama", "streamBlogCategory.movie_trailers"],
    category:["streamBlogCategory.history","streamBlogCategory.movy", "streamBlogCategory.trailer" ,"streamBlogCategory.tv_series"],
  },
];

export const blogsGrid = [
  {
    id: 1,
    thumbnail: generateImgPath("/assets/images/blog/rebirth-of-the-realm.webp"),
    blogDate: "January 10, 2025",
    userImage: generateImgPath("/assets/images/user/user3.webp"),
    username: "streamAccount.jenny",
    slug: "the-most-anticipated-movies",
    title: "streamBlog.blog1",
    description:"streamBlog.blog1_desc",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "streamBlogCategory.drama",
    tags: ["streamBlogTag.comedies", "streamTag.drama", "streamBlogCategory.movie_trailers"],
    category:["streamBlogCategory.history","streamBlogCategory.movy", "streamBlogCategory.trailer" ,"streamBlogCategory.tv_series"],
  },
  {
    id: 2,
    thumbnail: generateImgPath("/assets/images/blog/Special-Effects.webp"),
    blogDate: "January 10, 2025",
    userImage: generateImgPath("/assets/images/user/user3.webp"),
    username: "streamAccount.jenny",
    slug: "the-most-anticipated-movies",
    title: "streamBlog.blog2",
    description:"streamBlog.blog2_desc",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "streamBlogCategory.drama",
    tags: ["streamBlogTag.comedies", "streamTag.drama", "streamBlogCategory.movie_trailers"],
    category:["streamBlogCategory.history","streamBlogCategory.movy", "streamBlogCategory.trailer" ,"streamBlogCategory.tv_series"],
  },
  {
    id: 3,
    thumbnail: generateImgPath("/assets/images/blog/to-be-continue.webp"),
    blogDate: "January 10, 2025",
    userImage: generateImgPath("/assets/images/user/user3.webp"),
    username: "streamAccount.jenny",
    slug: "the-most-anticipated-movies",
    title: "streamBlog.blog3",
    description:"streamBlog.blog3_desc",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "streamBlogCategory.drama",
    tags: ["streamBlogTag.comedies", "streamTag.drama", "streamBlogCategory.movie_trailers"],
    category:["streamBlogCategory.history","streamBlogCategory.movy", "streamBlogCategory.trailer" ,"streamBlogCategory.tv_series"],
  },
  {
    id: 4,
    thumbnail: generateImgPath("/assets/images/blog/duos-standing.webp"),
    blogDate: "January 10, 2025",
    userImage: generateImgPath("/assets/images/user/user3.webp"),
    username: "streamAccount.jenny",
    slug: "the-most-anticipated-movies",
    title: "streamBlog.blog4",
    description:"streamBlog.blog4_desc",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "streamBlogCategory.drama",
    tags: ["streamBlogTag.comedies", "streamTag.drama", "streamBlogCategory.movie_trailers"],
    category:["streamBlogCategory.history","streamBlogCategory.movy", "streamBlogCategory.trailer" ,"streamBlogCategory.tv_series"],
  },
  {
    id: 5,
    thumbnail: generateImgPath("/assets/images/blog/short-movie.webp"),
    blogDate: "January 10, 2025",
    userImage: generateImgPath("/assets/images/user/user3.webp"),
    username: "streamAccount.jenny",
    slug: "the-most-anticipated-movies",
    title: "streamBlog.blog5",
    description:"streamBlog.blog5_desc",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "streamBlogCategory.drama",
    tags: ["streamBlogTag.comedies", "streamTag.drama", "streamBlogCategory.movie_trailers"],
    category:["streamBlogCategory.history","streamBlogCategory.movy", "streamBlogCategory.trailer" ,"streamBlogCategory.tv_series"],
  },
  {
    id: 6,
    thumbnail: generateImgPath("/assets/images/blog/beloved.webp"),
    blogDate: "January 10, 2025",
    userImage: generateImgPath("/assets/images/user/user3.webp"),
    username: "streamAccount.jenny",
    slug: "the-most-anticipated-movies",
    title: "streamBlog.blog6",
    description:"streamBlog.blog6_desc",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "streamBlogCategory.drama",
    tags: ["streamBlogTag.comedies", "streamTag.drama", "streamBlogCategory.movie_trailers"],
    category:["streamBlogCategory.history","streamBlogCategory.movy", "streamBlogCategory.trailer" ,"streamBlogCategory.tv_series"],
  },
  {
    id: 7,
    thumbnail: generateImgPath("/assets/images/blog/blog9.webp"),
    blogDate: "January 10, 2025",
    userImage: generateImgPath("/assets/images/user/user3.webp"),
    username: "streamAccount.jenny",
    slug: "the-most-anticipated-movies",
    title: "streamBlog.blog7",
    description:"streamBlog.blog7_desc",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "streamBlogCategory.drama",
    tags: ["streamBlogTag.comedies", "streamTag.drama", "streamBlogCategory.movie_trailers"],
    category:["streamBlogCategory.history","streamBlogCategory.movy", "streamBlogCategory.trailer" ,"streamBlogCategory.tv_series"],
  },
  {
    id: 8,
    thumbnail: generateImgPath("/assets/images/blog/blog8.webp"),
    blogDate: "January 10, 2025",
    userImage: generateImgPath("/assets/images/user/user3.webp"),
    username: "streamAccount.jenny",
    slug: "the-most-anticipated-movies",
    title: "streamBlog.blog8",
    description:"streamBlog.blog8_desc",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "streamBlogCategory.drama",
    tags: ["streamBlogTag.comedies", "streamTag.drama", "streamBlogCategory.movie_trailers"],
    category:["streamBlogCategory.history","streamBlogCategory.movy", "streamBlogCategory.trailer" ,"streamBlogCategory.tv_series"],
  },
  {
    id: 9,
    thumbnail: generateImgPath("/assets/images/blog/Independent.webp"),
    blogDate: "January 10, 2025",
    userImage: generateImgPath("/assets/images/user/user3.webp"),
    username: "streamAccount.jenny",
    slug: "the-most-anticipated-movies",
    title: "streamBlog.blog9",
    description:"streamBlog.blog9_desc",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "streamBlogCategory.drama",
    tags: ["streamBlogTag.comedies", "streamTag.drama", "streamBlogCategory.movie_trailers"],
    category:["streamBlogCategory.history","streamBlogCategory.movy", "streamBlogCategory.trailer" ,"streamBlogCategory.tv_series"],
  },
  {
    id: 10,
    thumbnail: generateImgPath("/assets/images/blog/blog5.webp"),
    blogDate: "January 10, 2025",
    userImage: generateImgPath("/assets/images/user/user3.webp"),
    username: "streamAccount.jenny",
    slug: "the-most-anticipated-movies",
    title: "streamBlog.blog10",
    description:"streamBlog.blog10_desc",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "streamBlogCategory.drama",
    tags: ["streamBlogTag.comedies", "streamTag.drama", "streamBlogCategory.movie_trailers"],
    category:["streamBlogCategory.history","streamBlogCategory.movy", "streamBlogCategory.trailer" ,"streamBlogCategory.tv_series"],
  },

  {
    id: 11,
    thumbnail: generateImgPath("/assets/images/blog/blog4.webp"),
    blogDate: "January 10, 2025",
    userImage: generateImgPath("/assets/images/user/user3.webp"),
    username: "streamAccount.jenny",
    slug: "the-most-anticipated-movies",
    title: "streamBlog.blog11",
    description:"streamBlog.blog11_desc",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "streamBlogCategory.drama",
    tags: ["streamBlogTag.comedies", "streamTag.drama", "streamBlogCategory.movie_trailers"],
    category:["streamBlogCategory.history","streamBlogCategory.movy", "streamBlogCategory.trailer" ,"streamBlogCategory.tv_series"],
  },

  {
    id: 12,
    thumbnail: generateImgPath("/assets/images/blog/comedy-movie.webp"),
    blogDate: "January 10, 2025",
    userImage: generateImgPath("/assets/images/user/user3.webp"),
    username: "streamAccount.jenny",
    slug: "the-most-anticipated-movies",
    title: "streamBlog.blog12",
    description:"streamBlog.blog12_desc",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "streamBlogCategory.drama",
    tags: ["streamBlogTag.comedies", "streamTag.drama", "streamBlogCategory.movie_trailers"],
    category:["streamBlogCategory.history","streamBlogCategory.movy", "streamBlogCategory.trailer" ,"streamBlogCategory.tv_series"],
  },

  {
    id: 13,
    thumbnail: generateImgPath("/assets/images/blog/kisds-movie.webp"),
    blogDate: "January 10, 2025",
    userImage: generateImgPath("/assets/images/user/user3.webp"),
    username: "streamAccount.jenny",
    slug: "the-most-anticipated-movies",
    title: "streamBlog.blog13",
    description:"streamBlog.blog13_desc",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "streamBlogCategory.drama",
    tags: ["streamBlogTag.comedies", "streamTag.drama", "streamBlogCategory.movie_trailers"],
    category:["streamBlogCategory.history","streamBlogCategory.movy", "streamBlogCategory.trailer" ,"streamBlogCategory.tv_series"],
  },

  {
    id: 14,
    thumbnail: generateImgPath("/assets/images/blog/blog1.webp"),
    blogDate: "January 10, 2025",
    userImage: generateImgPath("/assets/images/user/user3.webp"),
    username: "streamAccount.jenny",
    slug: "the-most-anticipated-movies",
    title: "streamBlog.blog14",
    description:"streamBlog.blog14_desc",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "streamBlogCategory.drama",
    tags: ["streamBlogTag.comedies", "streamTag.drama", "streamBlogCategory.movie_trailers"],
    category:["streamBlogCategory.history","streamBlogCategory.movy", "streamBlogCategory.trailer" ,"streamBlogCategory.tv_series"],
  },
];
export const blogRecent = [
  filterBlog("the-most-anticipated-movies"),
  filterBlog("amy-adams-always-dreamed"),
  filterBlog("wandaVision-will-reveal-scarlet-witch’s-untapped-powers"),
].filter((item) => item !== undefined);
export const blogRecents = [
  filterBlog("the-most-anticipated-movies"),
  filterBlog("amy-adams-always-dreamed"),
  filterBlog("wandaVision-will-reveal-scarlet-witch’s-untapped-powers"),
  filterBlog("everything-you-need-to-know-about"),
  filterBlog("my-streaming-black-pearl"),
].filter((item) => item !== undefined);
