import { generateImgPath } from "./data";

export const heroSlider = [
  {
    id: 1,
    thumbnail: generateImgPath("/assets/images/shop/slider-01.webp"),
  },
  {
    id: 2,
    thumbnail: generateImgPath("/assets/images/shop/slider-02.webp"),
  },
  {
    id: 3,
    thumbnail: generateImgPath("/assets/images/shop/slider-03.webp"),
  },
];

export const category = [
  {
    id: 1,
    title: "streamShop.activeman",
    image: generateImgPath("/assets/images/shop/categories/01.webp"),
  },
  {
    id: 2,
    title: "streamShop.avengers",
    image: generateImgPath("/assets/images/shop/categories/02.webp"),
  },
  {
    id: 3,
    title: "streamShop.disney_world",
    image: generateImgPath("/assets/images/shop/categories/03.webp"),
  },
  {
    id: 4,
    title: "streamShop.fantasia",
    image: generateImgPath("/assets/images/shop/categories/04.webp"),
  },

  {
    id: 6,
    title: "streamShop.galaxy_heaven",
    image: generateImgPath("/assets/images/shop/categories/05.webp"),
  },
  {
    id: 7,
    title: "streamShop.ghost_spider",
    image: generateImgPath("/assets/images/shop/categories/06.webp"),
  },
  {
    id: 8,
    title: "streamShop.harry_david",
    image: generateImgPath("/assets/images/shop/categories/07.webp"),
  },
  {
    id: 9,
    title: "streamShop.haunted_halloween",
    image: generateImgPath("/assets/images/shop/categories/08.webp"),
  },
  {
    id: 10,
    title: "streamShop.studios",
    image: generateImgPath("/assets/images/shop/categories/09.webp"),
  },
  {
    id: 11,
    title: "streamShop.monster_house",
    image: generateImgPath("/assets/images/shop/categories/11.webp"),
  },
  {
    id: 12,
    title: "streamShop.quid_game",
    image: generateImgPath("/assets/images/shop/categories/12.webp"),
  },
  {
    id: 13,
    title: "streamShop.the_madrid",
    image: generateImgPath("/assets/images/shop/categories/14.webp"),
  },
  {
    id: 14,
    title: "streamShop.the_chapion",
    image: generateImgPath("/assets/images/shop/categories/15.webp"),
  },
];

export const products = [
  {
    id: 1,
    slug: "bag-pack",
    product_name: "streamShop.product1",
    thumbnail: generateImgPath("/assets/images/shop/product/01.webp"),
    descriptio: "streamShop.product1_desc",
    stock_status: "In Stock",
    tags: ["costume", "lighting"],
    sku: "Bag Pack",
    discount: "",
    price: "$48.00",
    final_price: "$28.00",
    customer_review: 2,
    is_sale: false,
    is_new: false,
    ratting: 4,
    additional_info: [
      {
        title: "",
        value: "",
        color: ["Green", "Yellow"],
        size: ["L", "M"],
      },
    ],
    created_at: "",
    category: ["streamShop.marvel_studios", "streamShop.uptight_birds"],
  },
  {
    id: 2,
    slug: "believe-mask",
    product_name: "streamShop.product2",
    thumbnail: generateImgPath("/assets/images/shop/product/02.webp"),
    descriptio:"streamShop.product2_desc",
    stock_status: "In Stock",
    tags: ["streamShopTag.camera", "streamShopTag.costume", "streamShop.studios"],
    sku: "streamShop.product2",
    discount: "",
    price: "",
    final_price: "$13.00",
    customer_review: 0,
    is_sale: false,
    is_new: false,
    ratting: 4.5,
    additional_info: [
      {
        title: "",
        value: "",
        color: ["Gray"],
        size: ["M", "S"],
      },
    ],
    created_at: "",
    category: ["streamShop.disney_world", "streamShop.marvel_studios", "streamShop.fantasia", "streamShop.the_madrid"],
  },
  {
    id: 3,
    slug: "black-bow",
    product_name: "streamShop.product3",
    thumbnail: generateImgPath("/assets/images/shop/product/03.webp"),
    descriptio:"streamShop.product3_desc",
    stock_status: "In Stock",
    tags: ["Lighting", "streamShop.studios"],
    sku: "logo-collection",
    discount: "",
    final_price: "$18.00 – $45.00",
    customer_review: 1,
    is_sale: true,
    is_new: false,
    ratting: 4,
    additional_info: [
      {
        title: "",
        value: "",
        color: [],
        size: ["M", "S"],
      },
    ],
    created_at: "",
    category: [
      "Activeman",
      "Avengers",
      "Harry-David",
      "Haunted-Halloween",
      "streamShop.marvel_studios",
      "streamShop.marvel_studios",
      "Quid-Game",
      "The-Flashv",
      "Warner-Bros-Films",
    ],
  },
  {
    id: 4,
    slug: "black-cap",
    product_name: "streamShop.product4",
    thumbnail: generateImgPath("/assets/images/shop/product/04.webp"),
    category: ["streamShop.marvel_studios", "harry-david", "warner-bros-films"],
    stock_status: "In Stock",
    descriptio: "streamShop.product4_desc",
    tags: ["streamShop.camera", "Production"],
    sku: "woo-beanie",
    discount: "",
    price: "$20.00",
    final_price: "$18.00",
    customer_review: 0,
    is_sale: false,
    is_new: true,
    ratting: 0,
    additional_info: [
      {
        title: "",
        value: "",
        color: ["Blue", "Gray", "Green", "Red", "Yellow"],
        size: ["l", "m", "s"],
      },
    ],
    created_at: "",
  },
  {
    id: 5,
    slug: "boxing-gloves",
    product_name: "streamShop.product5",
    thumbnail: generateImgPath("/assets/images/shop/product/05.webp"),
    descriptio: "streamShop.product5_desc",
    stock_status: "In Stock",
    tags: ["streamShop.lightning", "streamShop.production"],
    sku: "Gloves",
    discount: "",
    price: "$18.00",
    final_price: "$10.00",
    customer_review: 1,
    is_sale: false,
    is_new: false,
    ratting: 5,
    additional_info: [
      {
        title: "",
        value: "",
        color: ["black", "red", "yellow"],
        size: ["l", "m", "s"],
      },
    ],
    created_at: "",
    category: ["quid-game"],
  },
  {
    id: 6,
    slug: "carry-bag",
    product_name: "streamShop.product6",
    thumbnail: generateImgPath("/assets/images/shop/product/06.webp"),
    descriptio: "streamShop.product6_desc",
    stock_status: "In Stock",
    tags: ["production"],
    discount: "",
    price: "",
    final_price: "$18.00",
    customer_review: 0,
    is_sale: false,
    is_new: false,
    ratting: 0,
    additional_info: [
      {
        title: "",
        value: "",
        color: ["gray"],
        size: [],
      },
    ],
    created_at: "",
    category: ["harry-david", "warner-bros-films"],
  },
  {
    id: 7,
    slug: "cartoon-character",
    product_name: "streamShop.product7",
    thumbnail: generateImgPath("/assets/images/shop/product/07.webp"),
    descriptio: "streamShop.product7_desc",
    stock_status: "In Stock",
    tags: ["streamShop.studios"],
    discount: "",
    price: "",
    final_price: "$18.00",
    customer_review: 1,
    is_sale: false,
    is_new: false,
    ratting: 2,
    additional_info: [
      {
        title: "",
        value: "",
        color: [],
        size: [],
      },
    ],
    created_at: "",
    category: ["uptight-birds"],
  },
  {
    id: 8,
    slug: "coffee-cap",
    product_name: "streamShop.product8",
    thumbnail: generateImgPath("/assets/images/shop/product/08.webp"),
    descriptio: "streamShop.product8_desc",
    stock_status: "In Stock",
    tags: ["streamShop.studios"],
    discount: "",
    price: "",
    final_price: "$15.00",
    customer_review: 0,
    is_sale: false,
    is_new: false,
    ratting: 0,
    additional_info: [
      {
        title: "",
        value: "",
        color: [],
        size: ["l", "m", "s"],
      },
    ],
    created_at: "",
    category: ["galaxy-heaven"],
  },
  {
    id: 9,
    slug: "crown",
    product_name: "streamShop.product9",
    thumbnail: generateImgPath("/assets/images/shop/product/09.webp"),
    descriptio:"streamShop.product9_desc",
    stock_status: "In Stock",
    tags: ["streamShopTag.camera", "lighting"],
    discount: "",
    price: "$10.00",
    final_price: "$7.00",
    customer_review: 0,
    is_sale: false,
    is_new: false,
    ratting: 0,
    additional_info: [
      {
        title: "",
        value: "",
        color: [],
        size: [],
      },
    ],
    created_at: "",
    category: ["quid-game"],
  },
  {
    id: 10,
    slug: "daily-diary",
    product_name: "streamShop.product10",
    thumbnail: generateImgPath("/assets/images/shop/product/10.webp"),
    descriptio: "streamShop.product10_desc",
    stock_status: "In Stock",
    tags: ["costume", "production"],
    discount: "",
    price: "$20.00",
    final_price: "$18.00",
    customer_review: 0,
    is_sale: false,
    is_new: false,
    ratting: 0,
    additional_info: [
      {
        title: "",
        value: "",
        color: ["Blue", "Gray", "Green", "Red", "Yellow"],
        size: ["l", "m", "s"],
      },
    ],
    created_at: "",
    category: ["activeman"],
  },
   {
    id: 11,
    slug: "floral-badges",
    product_name: "streamShop.product11",
    thumbnail: generateImgPath("/assets/images/shop/product/11.webp"),
    descriptio:"streamShop.product11_desc",
    stock_status: "In Stock",
    tags: ["lighting", "production"],
    discount: "",
    price: "",
    final_price: "$20.00",
    customer_review: 0,
    is_sale: false,
    is_new: false,
    ratting: 0,
    additional_info: [
      {
        title: "",
        value: "",
        color: ["Blue", "Gray", "Green", "Red", "Yellow"],
        size: [],
      },
    ],
    created_at: "",
    category: ["galaxy-heaven"],
  },
];
export const filterCategory = (slug) =>
  category.find((item) => item.slug === slug);
export const categoryWiseProduct = (category) =>
  products.filter((item) => item.category.includes(category));
export const tagsWiseProduct = (tag) =>
  products.filter((item) => item.tags.includes(tag));

export const shopBannerSlider = [
  filterCategory("streamShop.activeman"),
  filterCategory("streamShop.avengers"),
  filterCategory("streamShop.disney_world"),
  filterCategory("streamShop.fantasia"),
  filterCategory("streamShop.galaxy-heaven"),
  filterCategory("streamShop.ghost-spider"),
  filterCategory("streamShop.harry-david"),
  filterCategory("streamShop.haunted-halloween"),
  filterCategory("streamShop.marvel_studios"),
  filterCategory("streamShop.monster-house"),
  filterCategory("streamShop.quid-game"),
  filterCategory("streamShop.the-flashv"),
  filterCategory("streamShop.the_madrid"),
  filterCategory("streamShop.the-champion"),
  filterCategory("streamShop.uptight-birds"),
  filterCategory("streamShop.warner-bros-films"),
];

export const filterProduct = (slug) =>
  products.find((item) => item.slug === slug);

export const newProduct = [
  filterProduct("bag-pack"),
  filterProduct("believe-mask"),
  filterProduct("black-bow"),
  filterProduct("black-cap"),
  filterProduct("boxing-gloves"),
  filterProduct("carry-bag"),
];
export const bestseller = [
  filterProduct("bag-pack"),
  filterProduct("believe-mask"),
  filterProduct("black-cap"),
  filterProduct("round-neck-t-shirt"),
  filterProduct("daily-diary"),
];

export const myWishlist = [
  filterProduct("black-bow"),
  filterProduct("spider-pillow"),
  filterProduct("round-neck-t-shirt"),
  filterProduct("harry-t-shirt"),
];

export const related_product = [
  filterProduct('bag-pack'),
  filterProduct("believe-mask"),
  filterProduct("crown"),
  filterProduct("black-cap"),
  filterProduct("boxing-gloves"),
  filterProduct("carry-bag"),
  filterProduct("cartoon-character"),
]

export const related_merchandise_product = [
  filterProduct("bag-pack"),
  filterProduct("believe-mask"),
  filterProduct("black-bow"),
  filterProduct("black-cap"),
  filterProduct("boxing-gloves"),
  filterProduct("carry-bag"),
  filterProduct('cartoon-character')
];

export const myCart = [filterProduct("bag-pack")];
